version: '3.3'

services:
   wordpress:
     build: .  # Construye la imagen a partir del Dockerfile en el directorio actual
     ports:
       - "8009:80"  # Mapeo de puertos
     volumes:
      - ".:/var/www/html"
     environment:
       WORDPRESS_DB_HOST: host.docker.internal  # Asegúrate de que la base de datos sea accesible
       WORDPRESS_DB_USER: root                  # Usuario de la base de datos
       WORDPRESS_DB_PASSWORD: ''                # Contraseña de la base de datos
       WORDPRESS_DB_NAME: nino_electronico      # Nombre de la base de datos

networks: 
    wordpress: 
      driver: bridge
